### ISSUE TITLE
Error while detecting new changes to Scss Files

### ISSUE THREAD

**Issue by jinuem** [michaelwayman/node-sass-chokidar#17] opened 2017-07-21 12:46 UTC
I am using this Sass watch in my create-react-app. Integrated as per the Create-React-App Documentation.

```
  "build-css": "node-sass-chokidar src/ -o src/",
  "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
```
When i do` npm run watch-css`, it starts watching for my Scss files and converts properly. When i tried to change any Scss file and I save the file, it detects the change and throws the Error. 

> Same Issue with 0.0.2 and 0.0.3

Attaching the Debug Log:

> 17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "watch-css"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error eli@0.1.0 watch-css: `npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive`
22 error Exit status 3221225477
23 error Failed at the eli@0.1.0 watch-css script 'npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the eli package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs eli
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls eli
23 error There is likely additional logging output above.

**Comment by jinuem** [comment] 2017-07-24 05:43
Any Updates?

**Comment by coreybrown89** [comment] 2017-07-25 14:44
@jinuem I am having a similar issue..

```
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.6.0/bin/node" "/usr/local/bin/npm" "run" "build-css"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! jk17@0.1.0 build-css: `node-sass-chokidar src/ -o src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jk17@0.1.0 build-css script 'node-sass-chokidar src/ -o src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jk17 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass-chokidar src/ -o src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jk17
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jk17
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cbrown/sites/_c50/justinkeller.dev-frontend/npm-debug.log
error Command failed with exit code 1.
```

**Comment by jinuem** [comment] 2017-07-25 17:31
If you find any Solutions, Please drop here
@coreybrown89

**Comment by michaelwayman** [comment] 2017-07-25 20:44
Hey would one of you mind trying `node-sass` instead of `node-sass-chokidar`and see if the issue persists?

**Comment by coreybrown89** [comment] 2017-07-25 22:08
@michaelwayman `node-sass` gives me the same error

**Comment by jinuem** [comment] 2017-07-26 06:14
@michaelwayman 
Yes,` node-sass` gives the same error.

**Comment by michaelwayman** [comment] 2017-07-26 10:33
OK, so node-sass-chokidar is built on top of node-sass, the only thing that is really different is the file-watcher.
Since node-sass is giving the same issue, I would guess that the issue is coming from an underlying issue within node-sass. This isn't really something that can be fixed from node-sass-chokidar, it needs to be resolved in node-sass first.

**Comment by michaelwayman** [comment] 2017-10-07 12:00
@jinuem @coreybrown89 does this issue still exist with node-sass? 
I'm closing for now, once they fix the issue on their end I will make sure node-sass-chokidar is updated as well

**Closed by michaelwayman** 2017-10-07 12:00 UTC

**Comment by jantoebes** [comment] 2017-11-09 21:35
hi @jinuem @coreybrown89 @michaelwayman just had the same issue. Could you position the `watch` and `recursive` after the `node-sass-chokidar`?

Like `npm run build-css && node-sass-chokidar --watch --recursive  src/ -o src/`

You can also try if there are no background `node` jobs running with `pkill -9 -f node`

Please let me know if this works :)

**Comment by SkillSmart** [comment] 2017-12-30 10:36
@jantoebes tried and not solving it for me
