### ISSUE TITLE
Error when editing sass files with emacs

### ISSUE THREAD

**Issue by nikolas** [michaelwayman/node-sass-chokidar#40] opened 2018-03-03 03:24 UTC
I'm editing files with emacs, and each time I make a change my sass watcher crashes like this:

```
Error: ENOENT: no such file or directory, stat '/home/nik/src/un-peer
/src/.#index.scss'
    at Object.fs.statSync (fs.js:972:11)
    at Graph.addFile (/home/nik/src/un-peer/node_modules/sass-graph/s
ass-graph.js:64:18)
    at /home/nik/src/un-peer/node_modules/sass-graph/sass-graph.js:54
:13
    at arrayEach (/home/nik/src/un-peer/node_modules/lodash/lodash.js
:508:11)
    at Function.forEach (/home/nik/src/un-peer/node_modules/lodash/lo
dash.js:9334:14)
    at new Graph (/home/nik/src/un-peer/node_modules/sass-graph/sass-
graph.js:53:7)
    at Object.module.exports.parseDir (/home/nik/src/un-peer/node_mod
ules/sass-graph/sass-graph.js:156:17)
    at buildGraph (/home/nik/src/un-peer/node_modules/node-sass-choki
dar/bin/node-sass-chokidar:238:23)
    at FSWatcher.<anonymous> (/home/nik/src/un-peer/node_modules/node
-sass-chokidar/bin/node-sass-chokidar:269:13)
    at FSWatcher.emit (events.js:127:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! un-peer@0.1.0 watch-css: `npm run build-css && node-sass-cho
kidar src/ -o src/ --watch --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the un-peer@0.1.0 watch-css script.
npm ERR! This is probably not a problem with npm. There is likely add
itional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nik/.npm/_logs/2018-03-03T03_19_28_182Z-debug.log
ERROR: "watch-css" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! un-peer@0.1.0 start: `npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the un-peer@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely add
itional logging output above.
```

I'm using the `npm run start` command from [create-react-app](https://github.com/facebook/create-react-app).

**Comment by michaelwayman** [comment] 2018-03-06 00:33
I think this is a duplicate of #24 which should now be fixed with version 1.0.0 so I am going to close this for now. Feel free to reopen the issue if you are still having problems.

**Closed by michaelwayman** 2018-03-06 00:33 UTC
